# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('PGUSER', '') %>
  password: <%= ENV['PGPASSWORD'] %>

development:
  <<: *default
  database: Apptus_development

test:
  <<: *default
  host: localhost
  url: <%= ENV['DATABASE_URL'] %>
  database: Apptus_test

production:
  <<: *default
  database: Apptus_production
  prepared_statements: false
  url: <%= ENV['DATABASE_URL'] %>
